### ISSUE TITLE
Homework 03 e17-18 is missing critical word from the text file

### ISSUE THREAD

**Issue by Lassi-Ahonen** [pohjus/introduction-to-programming-exercises-03#1]
The text file: [/e17-18/words.txt](../blob/main/homework/03/17-18/words.txt) is missing the word "ananaslonkero", can you fix?
:trollface:

**Comment by pohjus** [comment]
Added the word "ananaslonkero" to `/e17-18/words.txt`. See commit f1f26a8

Closes #1
